### ISSUE TITLE
Change symfony result method

### ISSUE THREAD

**Issue by axroth** [eliashaeussler/cache-warmup#1]
Hi Elias, 

I'm using your script to warm caches xmlsitemap based in a cron. Works as designed. Like it! Since we monitor those crons we see an issue when the crawler hits urls that don't work, for example with a 403 response. Would it be possible to change the Code in  /src/Command/CacheWarmupCommand.php line 231 to use a warning instead an error message? And if not, allow that to be set as a parameter to choose from?

Best, Axel

**Comment by eliashaeussler** [comment]
Hi @axroth,

at first, thanks for using the cache-warmup package :) I'm happy that it's useful for you.

Can you concretize what's your current issue here? What difference makes it for you if we use a warning instead of an error here? The exit codes are not be affected by a change in the output, so this should not really matter. Maybe give me some more information to fully understand the "problem" so we can decide together what's the best solution here :) Thanks in advance!

**Comment by axroth** [comment]
Hi @eliashaeussler , 

> The exit codes are not be affected by a change in the output,

That's what i thought in the beginning. But it seems to be different.

To give you the full picture, we do something like that:

1 12 * * * /xxx/var/www/public/vendor/eliashaeussler/cache-warmup/bin/cache-warmup 'https://www.xxx.de/sitemap.xml' -v >>/tmp/cache_warmup_4.log 2>&1 && curl -fsS --retry 5 -o /dev/null https://xxx.com/ping/ed709312-d638-4d23-adee-0048dbe21720

In a cron we trigger the warmup. Its output is send to a temporary log-file. The error codes are redirected to an external monitoring that alerts us if crons fail. The external monitoring (https://github.com/healthchecks/healthchecks) may also react on content of the log, not only the exit code ( i don't know).

**Comment by axroth** [comment]
I was wrong. Even if changing to Warning, the exit code still seems to indicate an issue. Do you have an idea where this can be influenced?

**Comment by eliashaeussler** [comment]
Hi @axroth, does your issue still exist?

**Comment by axroth** [comment]
Hi @eliashaeussler , yes, if a single url could not be warmed, for example as of 403 or 404, the entire process fails.

**Comment by eliashaeussler** [comment]
Alright, I added a new command option `--allow-failures`. Would be nice if you can test it with your setup. See #42

**Comment by axroth** [comment]
sure, i'd love to. Will you publish a new release?

**Comment by eliashaeussler** [comment]
Yes, I will do. Can you by chance give it a try before it gets released? You can require the branch with

```bash
composer require eliashaeussler/cache-warmup:"dev-feature/allow-failures as 0.7.10"
```

Tests are green so it should work anyways. Testing it in a real world example would be even better :)

**Comment by axroth** [comment]
unfortunately not:

`  Problem 1
    - Root composer.json requires eliashaeussler/cache-warmup dev-feature/allow-failures as 0.7.10 -> satisfiable by eliashaeussler/cache-warmup[dev-feature/allow-failures].
    - eliashaeussler/cache-warmup dev-feature/allow-failures requires guzzlehttp/guzzle ^7.0 -> found guzzlehttp/guzzle[dev-master, 7.0.0-beta.1, ..., 7.4.x-dev (alias of dev-master)] but the package is fixed to 6.5.5 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.`
    
    drupal 9 uses guzzle 6. That also means that we are not using the latest release of cache-warmup right now.

**Comment by eliashaeussler** [comment]
Ok, I'll merge and release it then. You can still use the Docker image (if possible) or switch to PHIVE to circumvent dependency issues.

**Comment by axroth** [comment]
late response, but thanks for those hints. It works.
