### ISSUE TITLE
[FEATURE] run forever option

### ISSUE THREAD

**Issue by danielslyman** [eliashaeussler/cache-warmup#138]
### Is your feature request related to a problem?

I would like to have the option to have the docker container run forever and periodically execute. 

https://github.com/Pixep/crowlet

This is another cache-warmer which I tried, I much prefer yours. I set at cronjob for now, but I feel like a "forever" option would be more elegant.

Thanks!
Daniel

### Describe the solution you'd like

I would love something like this:

docker run --rm -it eliashaeussler/cache-warmup:latest 'https://website.com/cache.xml' '--verbose' '--allow-failures' '-p' '--forever' '--wait-interval 1800'

### Describe alternatives you've considered

https://github.com/Pixep/crowlet

**Comment by eliashaeussler** [comment]
Hi @danielslyman, thanks for your feature request. This sounds like a good idea. I will have a look at it.

**Comment by eliashaeussler** [comment]
Hi @danielslyman, this feature will be part of the `2.0.0` release. See #208 for more details.

**Comment by eliashaeussler** [comment]
@danielslyman The `2.0.0` release is out now. Have fun with it 🚀

**Comment by danielslyman** [comment]
Thanks a lot! This amazing :)
