### ISSUE TITLE
[FEATURE] work with sitemap index

### ISSUE THREAD

**Issue by onlinebizsoft** [eliashaeussler/cache-warmup#268]
### Is your feature request related to a problem?

Many big stores will have multiple sitemaps file from a sitemap index..........

### Describe the solution you'd like

It is easier if we can pass the sitemap index and the script will read them well instead of passing multiple ones manually in the command

**Comment by eliashaeussler** [comment]
@onlinebizsoft Sitemap indexes are already supported. Have a look at the Google sitemap, for example, which is a sitemap index as well:

```bash
$ docker run --rm -it eliashaeussler/cache-warmup https://www.google.com/sitemap.xml --limit 10 --progress -v
Running cache warmup 2.3.0 by Elias Häußler and contributors.
Parsing sitemaps... Done

Parsed sitemaps
---------------

 DONE  https://www.google.com/sitemap.xml
 DONE  https://www.google.com/gmail/sitemap.xml
```

Do you miss a specific feature of sitemap indexes or is it just about parsing sitemap indexes in general?

**Comment by onlinebizsoft** [comment]
@eliashaeussler you are right I didnt know. You may update this to the document as well. I'm testing out and let you know if any issue.
