### ISSUE TITLE
[FEATURE] Reading sitemap from file

### ISSUE THREAD

**Issue by gkopec** [eliashaeussler/cache-warmup#297]
### Is your feature request related to a problem?

There is a problem with getting sitemap content if server is blocking requests from Guzzle.

### Describe the solution you'd like

Guzzle on most production environments is blocked by server rules so maybe you can think of an option to change a default behaviour of parsing sitemap to use file path instead URI?

**Comment by eliashaeussler** [comment]
Hi @gkopec, thanks for your feature requests. I've implemented local file handling and released it with `v2.5.0`. Read more at #298 and https://github.com/eliashaeussler/cache-warmup#sitemaps

**Comment by gkopec** [comment]
No way!!! @eliashaeussler thank you so much!!!

**Comment by gkopec** [comment]
@eliashaeussler can you maybe marge this changes to version 2.1.5? I am using 2.1.4 probably because of PHP 8.1 and can't get into 8.2 yet :(
