### ISSUE TITLE
[FEATURE] Add a parameter to configure the thereshold for response time

### ISSUE THREAD

**Issue by onlinebizsoft** [eliashaeussler/cache-warmup#301]
### Is your feature request related to a problem?

Sometime the server may get a problem during crawling, the crawler should stop

### Describe the solution you'd like

Add a threshold parameter to stop the crawler when response time is over that threshold

**Comment by eliashaeussler** [comment]
This should already be doable with Guzzle's [`timeout`](https://docs.guzzlephp.org/en/stable/request-options.html#timeout) request option. You can pass request options with the [`--crawler-options`](https://github.com/eliashaeussler/cache-warmup#--crawler-options) command option. The only thing left is that the crawler won't stop on timeouts. I may add an option `--stop-on-failure` or similar later, so this issue will be kept open.

**Comment by onlinebizsoft** [comment]
@eliashaeussler yes we need the script to stop because when that happen means the server may get overloading or some problems so we shouldn't continue

**Comment by eliashaeussler** [comment]
@onlinebizsoft I've implemented a new command option `--stop-on-failure`. You can use this in combination what I wrote in https://github.com/eliashaeussler/cache-warmup/issues/301#issuecomment-1792267349. This is released with version `2.7.0` of the library.
