### ISSUE TITLE
[QUESTION] Why it suddenly sends only HEAD request?

### ISSUE THREAD

**Issue by gkopec** [eliashaeussler/cache-warmup#311]
### PHP version

8.1

### Package version

2.5.0

### Application

Composer

### Operating system

Ubuntu

### Current behavior

From today I found in access.log that script is sending only HEAD without GET request. Could this be an nginx problem?
Without GET the cache is not warmin up actually.

**Comment by eliashaeussler** [comment]
Hi @gkopec, the crawler was always designed to send `HEAD` requests by default. However, you can always change the request method to `GET` (see https://github.com/eliashaeussler/cache-warmup#request_method).

Example for usage on the command-line:

```bash
$ vendor/bin/cache-warmup -o '{"request_method": "GET"}'
```
