### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by jamaluddinrumi** [eliashaeussler/cache-warmup#323]
### PHP version

-

### Package version

2.7.1

### Application

Docker

### Operating system

Ubuntu   22.04.3   LTS

### Current behavior

```php
In MalformedXmlException.php line 39:
                                                                               
  The string "{"total":1076}" does not contain valid XML: The string "{"total  
  ":1076}" does not contain valid XML: DOMDocument::loadXML(): Start tag expe  
  cted, '<' not found in Entity, line: 1        
```

![Artboard](https://github.com/eliashaeussler/cache-warmup/assets/446780/d31a1542-c0f9-458d-8a02-0e232edff54c)

**Comment by eliashaeussler** [comment]
Hi @jamaluddinrumi, can you elaborate on what the actual error is that you encountered? It looks to me like the response of the parsed XML sitemap is JSON instead of XML. This is of course something the parser cannot handle.

**Comment by jamaluddinrumi** [comment]
hi @eliashaeussler nice to having your reply. 

this is the sitemap https://www.indomascot.com/sitemap-index.xml 

is there anything wrong?

**Comment by jamaluddinrumi** [comment]
![Screenshot 2024-01-25 at 22 55 31](https://github.com/eliashaeussler/cache-warmup/assets/446780/3feb8aab-97e9-4ee4-aee9-6d64354fe348)

i got it

it's my mistakes

since `warm-cache` can only parse xml-like, i should not give it to parse json 😂
