### ISSUE TITLE
Basic auth

### ISSUE THREAD

**Issue by indrisepos** [eliashaeussler/cache-warmup#387]
### Is your feature request related to a problem?

The current documentation for the cache-warmup project does not mention how to configure basic authentication (basic auth) for secure access to the tool.

### Describe the solution you'd like

I would like the documentation to include a section that provides guidance on setting up and using basic auth with the cache-warmup project. This would help users like myself who need to secure access to the tool.

### Describe alternatives you've considered

Without the basic auth documentation, the only alternative would be to try to figure out the configuration on my own, which may be time-consuming and error-prone.

### Additional context

Providing clear instructions on basic auth integration would be a valuable addition to the project's documentation, making it more accessible and usable for a wider range of users who require secure access controls.

**Comment by indrisepos** [comment]
I found the solution:
`./cache-warmup.phar -u https://example.com/ --crawler-options '{"concurrency": 3, "client_config": {"auth": ["login", "password"]}}'`

**Comment by eliashaeussler** [comment]
Hi, I've added this to the FAQ section: https://cache-warmup.dev/faq.html#how-can-i-configure-basic-auth-credentials
