### ISSUE TITLE
[BUG] Fatal error with CuyZ/Valinor version 1.14.0

### ISSUE THREAD

**Issue by jcvignoli** [eliashaeussler/cache-warmup#409]
### PHP version

8.2

### Package version

3.2.0

### Application

Composer

### Operating system

6.1.0-0.deb11.21-amd64

### Current behavior

The update to composer CuyZ/Valinor version 1.14.0 broke Cache Warmup. I reversed to 1.13, and everything is fine.

Seems to me that addSitemaps() method (in Sitemap) doesn't work with new valinor release.

### Steps to reproduce

Use addSitemaps() method with a XML file

### Additional context

Here is the fatal error:

`Fatal error: Uncaught ReflectionException: Class "EliasHaeussler\CacheWarmup\Sitemap" does not exist in /linuxpath/vendor/cuyz/valinor/src/Utility/Reflection/Reflection.php:60 Stack trace: #0 /linuxpath/vendor/cuyz/valinor/src/Utility/Reflection/Reflection.php(60): ReflectionClass->__construct('EliasHaeussler\\...') #1 /linuxpath/vendor/cuyz/valinor/src/Type/Parser/Lexer/Token/ClassNameToken.php(41): CuyZ\Valinor\Utility\Reflection\Reflection::class('EliasHaeussler\\...') #2 /linuxpath/vendor/cuyz/valinor/src/Type/Parser/Lexer/Token/ObjectToken.php(23): CuyZ\Valinor\Type\Parser\Lexer\Token\ClassNameToken->__construct('EliasHaeussler\\...') #3 /linuxpath/vendor/cuyz/valinor/src/Type/Parser/Lexer/Token/VacantToken.php(30): CuyZ\Valinor\Type\Parser\Lexer\Token\ObjectToken->traverse(Object(CuyZ\Valinor\Type\Parser\Lexer\TokenStream)) #4 /linuxpath/vendor/cuyz/valinor/src/Type/Parser/Lexer/TokenStream.php(36): CuyZ\Valinor\Type\Parser\Lexer\Token\VacantToken->traverse(Object(CuyZ\Valinor\Type\Parser\Lexer\TokenStream)) #5 /linuxpath/vendor/cuyz/valinor/src/Type/Parser/Lexer/Token/ListToken.php(41): CuyZ\Valinor\Type\Parser\Lexer\TokenStream->read() #6 /linuxpath/vendor/cuyz/valinor/src/Type/Parser/Lexer/TokenStream.php(36): CuyZ\Valinor\Type\Parser\Lexer\Token\ListToken->traverse(Object(CuyZ\Valinor\Type\Parser\Lexer\TokenStream)) #7 /linuxpath/vendor/cuyz/valinor/src/Type/Parser/LexingParser.php(22): CuyZ\Valinor\Type\Parser\Lexer\TokenStream->read() #8 /linuxpath/vendor/cuyz/valinor/src/Type/Parser/GenericCheckerParser.php(32): CuyZ\Valinor\Type\Parser\LexingParser->parse('list<Sitemap\\Si...') #9 /linuxpath/vendor/cuyz/valinor/src/Definition/Repository/Reflection/TypeResolver/ReflectionTypeResolver.php(81): CuyZ\Valinor\Type\Parser\GenericCheckerParser->parse('list<Sitemap\\Si...') #10 /linuxpath/vendor/cuyz/valinor/src/Definition/Repository/Reflection/TypeResolver/ReflectionTypeResolver.php(32): CuyZ\Valinor\Definition\Repository\Reflection\TypeResolver\ReflectionTypeResolver->parseType('list<Sitemap\\Si...', Object(CuyZ\Valinor\Type\Parser\GenericCheckerParser)) #11 /linuxpath/vendor/cuyz/valinor/src/Definition/Repository/Reflection/TypeResolver/ParameterTypeResolver.php(34): CuyZ\Valinor\Definition\Repository\Reflection\TypeResolver\ReflectionTypeResolver->resolveType(Object(ReflectionNamedType), 'list<Sitemap\\Si...') #12 /linuxpath/vendor/cuyz/valinor/src/Definition/Repository/Reflection/ReflectionParameterDefinitionBuilder.php(27): CuyZ\Valinor\Definition\Repository\Reflection\TypeResolver\ParameterTypeResolver->resolveTypeFor(Object(ReflectionParameter)) #13 /linuxpath/vendor/cuyz/valinor/src/Definition/Repository/Reflection/ReflectionMethodDefinitionBuilder.php(39): CuyZ\Valinor\Definition\Repository\Reflection\ReflectionParameterDefinitionBuilder->for(Object(ReflectionParameter), Object(CuyZ\Valinor\Definition\Repository\Reflection\TypeResolver\ReflectionTypeResolver)) #14 [internal function]: CuyZ\Valinor\Definition\Repository\Reflection\ReflectionMethodDefinitionBuilder->CuyZ\Valinor\Definition\Repository\Reflection\{closure}(Object(ReflectionParameter)) #15 /linuxpath/vendor/cuyz/valinor/src/Definition/Repository/Reflection/ReflectionMethodDefinitionBuilder.php(38): array_map(Object(Closure), Array) #16 /linuxpath/vendor/cuyz/valinor/src/Definition/Repository/Reflection/ReflectionClassDefinitionRepository.php(107): CuyZ\Valinor\Definition\Repository\Reflection\ReflectionMethodDefinitionBuilder->for(Object(ReflectionMethod), Object(CuyZ\Valinor\Definition\Repository\Reflection\TypeResolver\ReflectionTypeResolver)) #17 [internal function]: CuyZ\Valinor\Definition\Repository\Reflection\ReflectionClassDefinitionRepository->CuyZ\Valinor\Definition\Repository\Reflection\{closure}(Object(ReflectionMethod)) #18 /linuxpath/vendor/cuyz/valinor/src/Definition/Repository/Reflection/ReflectionClassDefinitionRepository.php(104): array_map(Object(Closure), Array) #19 /linuxpath/vendor/cuyz/valinor/src/Definition/Repository/Reflection/ReflectionClassDefinitionRepository.php(68): CuyZ\Valinor\Definition\Repository\Reflection\ReflectionClassDefinitionRepository->methods(Object(CuyZ\Valinor\Type\Types\NativeClassType)) #20 /linuxpath/vendor/cuyz/valinor/src/Definition/Repository/Cache/CacheClassDefinitionRepository.php(32): CuyZ\Valinor\Definition\Repository\Reflection\ReflectionClassDefinitionRepository->for(Object(CuyZ\Valinor\Type\Types\NativeClassType)) #21 /linuxpath/vendor/cuyz/valinor/src/Mapper/Tree/Builder/InterfaceNodeBuilder.php(55): CuyZ\Valinor\Definition\Repository\Cache\CacheClassDefinitionRepository->for(Object(CuyZ\Valinor\Type\Types\NativeClassType)) #22 /linuxpath/vendor/cuyz/valinor/src/Mapper/Tree/Builder/CasterProxyNodeBuilder.php(30): CuyZ\Valinor\Mapper\Tree\Builder\InterfaceNodeBuilder->build(Object(CuyZ\Valinor\Mapper\Tree\Shell), Object(CuyZ\Valinor\Mapper\Tree\Builder\RootNodeBuilder)) #23 /linuxpath/vendor/cuyz/valinor/src/Mapper/Tree/Builder/IterableNodeBuilder.php(26): CuyZ\Valinor\Mapper\Tree\Builder\CasterProxyNodeBuilder->build(Object(CuyZ\Valinor\Mapper\Tree\Shell), Object(CuyZ\Valinor\Mapper\Tree\Builder\RootNodeBuilder)) #24 /linuxpath/vendor/cuyz/valinor/src/Mapper/Tree/Builder/StrictNodeBuilder.php(34): CuyZ\Valinor\Mapper\Tree\Builder\IterableNodeBuilder->build(Object(CuyZ\Valinor\Mapper\Tree\Shell), Object(CuyZ\Valinor\Mapper\Tree\Builder\RootNodeBuilder)) #25 /linuxpath/vendor/cuyz/valinor/src/Mapper/Tree/Builder/ErrorCatcherNodeBuilder.php(33): CuyZ\Valinor\Mapper\Tree\Builder\StrictNodeBuilder->build(Object(CuyZ\Valinor\Mapper\Tree\Shell), Object(CuyZ\Valinor\Mapper\Tree\Builder\RootNodeBuilder)) #26 /linuxpath/vendor/cuyz/valinor/src/Mapper/Tree/Builder/RootNodeBuilder.php(16): CuyZ\Valinor\Mapper\Tree\Builder\ErrorCatcherNodeBuilder->build(Object(CuyZ\Valinor\Mapper\Tree\Shell), Object(CuyZ\Valinor\Mapper\Tree\Builder\RootNodeBuilder)) #27 /linuxpath/vendor/cuyz/valinor/src/Mapper/TypeTreeMapper.php(49): CuyZ\Valinor\Mapper\Tree\Builder\RootNodeBuilder->build(Object(CuyZ\Valinor\Mapper\Tree\Shell)) #28 /linuxpath/vendor/cuyz/valinor/src/Mapper/TypeTreeMapper.php(29): CuyZ\Valinor\Mapper\TypeTreeMapper->node('EliasHaeussler\\...', Object(CuyZ\Valinor\Mapper\Source\Source)) #29 /linuxpath/eliashaeussler/cache-warmup/src/Xml/XmlParser.php(100): CuyZ\Valinor\Mapper\TypeTreeMapper->map('EliasHaeussler\\...', Object(CuyZ\Valinor\Mapper\Source\Source)) #30 /linuxpath/eliashaeussler/cache-warmup/src/CacheWarmer.php(155): EliasHaeussler\CacheWarmup\Xml\XmlParser->parse(Object(EliasHaeussler\CacheWarmup\Sitemap\Sitemap)) #31 /linuxpath/class/Admini/Webcron/Libs/WarmCache.php(91): EliasHaeussler\CacheWarmup\CacheWarmer->addSitemaps(Array) #32 /linuxpath/class/Admini/Webcron/Jobs/Daily.php(194): localclass\Admini\Webcron\Libs\WarmCache->start(Array) #33 /linuxpath/class/Admini/Webcron/Jobs/Daily.php(59): localclass\Admini\Webcron\Jobs\Daily->siteCacheWarming(Object(localclass\Admini\Webcron\Libs\WarmCache)) #34 /linuxpath/class/Services/Cron.php(100): localclass\Admini\Webcron\Jobs\Daily->start() #35 /linuxpath/class/Services/Cron.php(108): localclass\Services\Cron->startCron() #36 {main} thrown in /linuxpath/vendor/cuyz/valinor/src/Utility/Reflection/Reflection.php on line 60`

**Comment by eliashaeussler** [comment]
Yes, #408 is also failing. Didn't have the time for further investigation. I'll check it out the next days.

**Comment by eliashaeussler** [comment]
Hi @jcvignoli, I've marked `cuyz/valinor` v1.14.0 as conflicting and released a new version. You should be safe to update now.

**Comment by jcvignoli** [comment]
Thank you @eliashaeussler!
